# Intro to Python


*   Python is a general-purpose programming language, not designed for one task (compared to R --> data analysis)
*   The pandas library does most of the work of R


## Packages/libraries
*   A python pacakge is a reusable collection of code that you install.
*   Collab comes with most packages pre-installed so we just need to import

## Imports


*   Use import to import a library
*   Use as to refer to the library by a nickname
*   Use from ___ import ____ to import a single method or function from a library.
*   Whatever is stated last will be how you refer to object

In [4]:
import os
import pandas as pd
from openai import OpenAI

# Collab set up

In [7]:
from google.colab import drive
from google.colab import userdata
drive.mount('/content/drive/')

Mounted at /content/drive/

In [10]:
os.chdir("./drive/MyDrive/")
# !git clone https://github.com/hernandezb3/llm-text-classification.git

In [11]:
os.listdir("./llm-text-classification/data/")

['.gitignore', 'test.xlsx', 'train.xlsx', 'dev.xlsx']

In [13]:
os.environ["HF_TOKEN"] = userdata.get('HF_TOKEN')
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

# Programming tools


*   Values
*   Actions: Operations, Functions, and Methods
*   Repetition (e.g., loops)
*   Conditional execution (if statements, try/except)

# Variable


*   A variable is a name that refers to a value
*   Any length and can contain letters, numbers, and _. They can’t begin with a number.

In [15]:
n = 2
2 + n

4

In [16]:
MODEL = "gpt-5.6-terra"

# Primitive value types


*   one of the basic things Python works with – like a letter or a number
*   Four primitive value types in Python: float, integer, string, boolean

## Floats and integers


*   A float is a number, positive or negative, with one or more decimals.
*   An integer is a whole number, positive or negative, without decimals.

In [18]:
n = 2
type(n)

int

In [19]:
n = 2.0
type(n)

float

## Strings


*   Any value surrounded by quotation marks is a string
*   A float is a number, positive or negative, with one or more decimals.

In [20]:
mystring = "hello, aime-con"

In [21]:
type(mystring)

str

In [22]:
mystring = "2"
type(mystring)

str

## Boolean


*   Take ones of two values: True or False.
*   Most commonly, Boolean values are useful as output. You ask Python something and it says true or false.

In [24]:
2 == 3

False

# Simple operations


*   Operators are special symbols that represent computations like addition and multiplication
*   E.g., +, -, *, /, **(exponentiation)

In [25]:
2 + 3 == 5

True


*   The + is the only mathematical operation that can be used with a string.
*   It will concatenate two strings.

In [29]:

INTRO_PROMPT = """Classify the following utterance as yes or no based on whether it is a dialogic prompt.
A dialogic prompt is defined as an utterance that implies, encourages, requests, or expects a
new speaker (or multiple new speakers) to make a verbal contribution.\n
Here is the utterance: """ # """ lets our string go to the next line. just useful for reading code.

text_case = "Okay, and what would you do?"


prompt = INTRO_PROMPT + text_case
print(prompt)

Classify the following utterance as yes or no based on whether it is a dialogic prompt.
A dialogic prompt is defined as an utterance that implies, encourages, requests, or expects a
new speaker (or multiple new speakers) to make a verbal contribution.

Here is the utterance: Okay, and what would you do?

## Comparison operators
+ Comparison operators compare two values and return a Boolean.
+ E.g., <, <=, >, >=, ==, !=

In [30]:
2 < 3

True

In [31]:
2 == 3 # note ==, not =. = is an assignment operator

False

# Brackets
+ Brackets are special symbols in Python that perform indexing; accessing an item by its position.
+ E.g. You can access a character in a string by its position using brackets
+ Indexing in Python begins at zero.
+ I.e., you count 0, 1, 2, 3…

In [34]:
text_case

'Okay, and what would you do?'

In [35]:
text_case[0]

'O'

Together, brackets and a colon perform slicing on strings; returning a portion of the string with the following syntax [start:uptonotincluding]

In [37]:
text_case[0:4]

'Okay'

Negative indexing starts in the last position, labelled -1

In [41]:
text_case[-4:]

' do?'

Membership operators ask if a sequence is present in an object. There are two membership operators in and not in.

In [43]:
"Okay" in text_case

True

# Functions
+ A function is a named sequence of statements (code). Later, you can “call” the function by name.
+ E.g. print() is an example built-in function in Python.
+ A function often “takes” an argument and returns a result.
+ A function often “takes” an argument and returns a result.

In [44]:
print(text_case)

Okay, and what would you do?

+ E.g.  str() converts its argument to a string

In [47]:
not_a_string = 2
now_a_string = str(not_a_string)
print(type(now_a_string))
print(now_a_string)

<class 'str'>
2

+ You can create your own functions using a definition statement - def
+ All statements within the function need to be indented.
+ All statements within the function need to be indented.
+ To call the function, you just type the name plus parentheses.

In [48]:
def print_lyrics():
  print("Home is where I want to be")
  print("Pick me up and turn me round")

In [49]:
print_lyrics()

Home is where I want to be
Pick me up and turn me round

A fruitful function returns a value. This requires a return statement.

In [50]:
def add_two(starting_number):
  new_value = starting_number + 2
  return new_value

In [51]:
add_two(3)

5

# Methods
+ A method is like a function but it is associated with a particular object (value type) and is called using dot notation.
+ E.g., there are string methods and pandas methods
+ With dot notation, instead of putting the input inside the parentheses, you put the input ahead of the method followed by a dot.
+ E.g. The following string method will return upper case of the word, banana

In [67]:
word = "banana"
upper_word = word.upper()
print(upper_word)

BANANA

# Classes
+ A class defines a new kind of value.

In [68]:
from enum import Enum # defines a fixed set of allowed choices

class Answer(str, Enum): # create a new type of thing called an answer. because we are using Enum, that new thing can only take the values we list
    yes = "yes"
    no = "no"

my_answer = Answer.yes # from Answer, grab yes. dot accesses something belonging to the object or class named before it

print(my_answer)        # Answer.yes
print(my_answer.value)  # yes

Answer.yes
yes

# Conditionals

## If statements
+ If statements allow us to check conditions and change the behavior of a program accordingly
+ If statements contain a header – an “if” followed by a Boolean expression – and then an indented body

In [69]:
talking_heads_fan = True
if talking_heads_fan:
  print_lyrics()

Home is where I want to be
Pick me up and turn me round

## Try/except
+ Tell python to first try to run some code, if error pops up, run different code

In [70]:
starting_number = "I don't know"
add_two(starting_number)

TypeError: can only concatenate str (not "int") to str

In [71]:
starting_number = "I don't know"
try:
  add_two(starting_number)
except:
  print("Did you provide a float or int to starting_number?")

Did you provide a float or int to starting_number?

# Collection values

## A list is an ordered set of items
+ Items can be any data type
+ Items in a list are separated by a comma and the list is surrounded by brackets

In [72]:
mylist = [2, "yes", False]

## Dictionary
+ A dictionary is an unordered mapping of keys to values.
+ Each key is associated with a value. Together they form key-value pairs. You can also think of this like a database entry with a question and answer for an observation.
+ A dictionary is surrounded by braces (curly brackets), with each key to the left of brackets and each value to the right. Key-value pairs are separated by a comma

In [73]:
text_to_integer = {"one": 1, "two": 2, "three": 3}

+ You “look-up” a value in the dictionary by indexing the dictionary by the key.
+ Indexing a dictionary uses the same operation as indexing a string – brackets

In [74]:
text_to_integer["one"]

1

# Tuple
* Tuples are like lists that cannot be changed.
+ Tuples are surrounded by parentheses rather than brackets.

In [84]:
mytuple = (1,2,3,4)

In [85]:
tuple[0]

tuple[0]

# Loops

A for loop iterates over a set of items.
+ In each iteration the looped variable is set to a value in a sequence or collection
+ Strings, lists, and dictionaries are all iterable

In [78]:
animals = ["cat", "dog", "bird"]
for animal in animals:
	print(animal)

cat
dog
bird

# All together with LLMs

In [94]:
# initialize the model
openai = OpenAI()

# Save your variables as a string
system_prompt = "You are a Talking Heads fan."
user_prompt = "Name a song by the Talking Heads."
PROMPT = [
    {"role": "user", "system": system_prompt, "content": user_prompt}
  ]

# model settings
# openai has a thing called chat, which has a thing called completions, which has a method called create. create takes arguements including...
client = openai.chat.completions.create(
    model = MODEL,
    messages = PROMPT,
    n = 3,
    temperature = 1
    )

client # this is an OpenAI object (created with a class). It contains lots of things we can access with dot notation

ChatCompletion(id='chatcmpl-EVFigd1gt02ym4kYJSqdX7lt9nlKt', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='“Once in a Lifetime”', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None)), Choice(finish_reason='stop', index=1, logprobs=None, message=ChatCompletionMessage(content='“Once in a Lifetime”', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None)), Choice(finish_reason='stop', index=2, logprobs=None, message=ChatCompletionMessage(content='“Once in a Lifetime”', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None))], created=1791117302, model='gpt-5.6-terra', object='chat.completion', moderation=None, service_tier='default', system_fingerprint=None, usage=CompletionUsage(completion_tokens=27, prompt_tokens=14, total_tokens=41, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=0), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cache_write_tokens=0, cached_tokens=0)))

In [95]:
client.choices

[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='“Once in a Lifetime”', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None)),
 Choice(finish_reason='stop', index=1, logprobs=None, message=ChatCompletionMessage(content='“Once in a Lifetime”', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None)),
 Choice(finish_reason='stop', index=2, logprobs=None, message=ChatCompletionMessage(content='“Once in a Lifetime”', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None))]

In [96]:
client.choices[0]

Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='“Once in a Lifetime”', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None))

In [97]:
client.choices[0].message

ChatCompletionMessage(content='“Once in a Lifetime”', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None)

In [98]:
client.choices[0].message.content

'“Once in a Lifetime”'

In [99]:
for response in client.choices:
  print(response.message.content)

“Once in a Lifetime”
“Once in a Lifetime”
“Once in a Lifetime”

In [105]:
client = openai.chat.completions.create(
    model = "gpt-5.4",
    messages = PROMPT,
    n = 5,
    temperature = 2
    )

for response in client.choices:
  print(response.message.content)

“Psycho Killer.”
“Once in a Lifetime.”
“Psycho Killer.”
“Psycho Killer.”
“Psycho Killer” is a song by Talking Heads.

# Pandas
+ Pandas introduces the two new python datatypes --> series, dataframe
+ A data frame is a two-dimensional labelled data structure with columns of potentially different types
+ I.e. a dataset with rows, columns, and an index

In [116]:
dict_for_df = {
    "song_title": [
        "Once in a Lifetime",
        "This Must Be the Place",
        "Purple Rain",
        "Dancing Queen"
    ],
    "artist": [
        "Talking Heads",
        "Talking Heads",
        "Prince",
        "ABBA"
    ]
}

df = pd.DataFrame(dict_for_df, columns=["song_title", "artist"])

In [117]:
df

               song_title         artist
0      Once in a Lifetime  Talking Heads
1  This Must Be the Place  Talking Heads
2             Purple Rain         Prince
3           Dancing Queen           ABBA

## Series
+ A pandas series is one-dimensional labelled array capable of holding any value type
+ Very similar to a list

In [125]:
df.artist

0    Talking Heads
1    Talking Heads
2           Prince
3             ABBA
Name: artist, dtype: object

In [126]:
df.artist[0]

'Talking Heads'

## loc
+ loc indexes a dataframe by row, column

In [127]:
df.loc[df.artist== "ABBA"]

      song_title artist
3  Dancing Queen   ABBA

In [128]:
df.loc[df.artist== "ABBA", "song_title"]

3    Dancing Queen
Name: song_title, dtype: object

In [129]:
df.loc[df.artist== "ABBA", "song_title"].item() # item takes the single value out of the selected pandas Series

'Dancing Queen'

## F-strings
+ F-strings let you insert values into text.
+ Put f before the quotation mark and place variables inside {}.

In [132]:
song = "Dancing Queen"
artist = "ABBA"

message = f"{song} is by {artist}."
message

'Dancing Queen is by ABBA.'

In [130]:
# remember our class
class Answer(str, Enum):
    yes = "yes"
    no = "no"

# Bringing things together again

In [134]:
df

               song_title         artist
0      Once in a Lifetime  Talking Heads
1  This Must Be the Place  Talking Heads
2             Purple Rain         Prince
3           Dancing Queen           ABBA

In [135]:
for row in df.index:
  print(row)

0
1
2
3

In [137]:
responses = []

for row in df.index:

    song_title = df.loc[row, "song_title"]
    artist = df.loc[row, "artist"]

    user_prompt = f"""
    Song title: {song_title}
    Artist: {artist}

    Is this song by Talking Heads?
    Respond with only yes or no.
    """

    prompt = [
        {"role": "user", "content": user_prompt}
    ]

    completion = openai.chat.completions.create(
        model=MODEL,
        messages=prompt
    )

    response_text = completion.choices[0].message.content
    print(response_text)
    answer = Answer(response_text.strip().lower())

    responses.append(answer.value)


df["talking_heads"] = responses

df

yes
yes
no
no

               song_title         artist talking_heads
0      Once in a Lifetime  Talking Heads           yes
1  This Must Be the Place  Talking Heads           yes
2             Purple Rain         Prince            no
3           Dancing Queen           ABBA            no